In [1]:
from Problem import Problem
from Algorithm import VariableNeighborhoodSearch
from Neighborhood import Swap, Reversion, Insertion, Slide, ETN, RS, SPS, SRPS, FixedCostSwap, TransportCostSwap
from Solution import Solution
import pickle
import copy
import numpy as np

data = Problem()
data.loadFile("../data/data_10.npz")

with open("../solution_test.pickle", "rb") as f:
    solution = pickle.load(f)
solution.evaluate(data)
print("Initial solution cost:", solution.FX)

Initial solution cost: 10257396.618116293


In [2]:
new_solution = copy.deepcopy(solution)

# Helper to swap bits in a 1D binary array
def swap_bits(arr, idx_remove, idx_add):
    lst = list(arr)
    lst[idx_remove], lst[idx_add] = lst[idx_add], lst[idx_remove]
    return np.array(lst)

chromosome_attr, chromosome = 'S1', solution.S1  # Example for Pistachio Factories -> Pistachio Consumers
row_mask = chromosome  # binary vector representing active(1)/inactive(0)

print(f"Initial chromosome: {chromosome}")
print(f"Transportation Matrix: {solution.P}")
print(f"Demand: {data.Dp}")
print(f"Transportation Costs:")
print(np.array2string(data.Cp, formatter={'float_kind':lambda x: "%.2f" % x}))


Initial chromosome: [ 3  6 12 15  5 11 17  4  8 16 13  9  1 14 18 19 20  7  2 10]
Transportation Matrix: <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (10, 10)>
  Coords	Values
  (1, 4)	317.87618526202857
  (1, 5)	288.982920204273
  (1, 6)	265.6230251334098
  (6, 0)	211.73332004057494
  (6, 1)	204.28774604208115
  (6, 2)	335.8842168585896
  (6, 3)	274.75642490782286
  (6, 7)	303.89009511299315
  (6, 8)	246.62697684610652
  (6, 9)	344.68405258353096
Demand: [211.73332004 204.28774604 335.88421686 274.75642491 317.87618526
 288.9829202  265.62302513 303.89009511 246.62697685 344.68405258]
Transportation Costs:
[[30.41 31.07 34.68 35.01 29.34 35.16 23.77 29.25 37.72 30.41]
 [32.17 36.21 37.56 29.97 25.97 30.62 32.64 35.31 20.90 30.70]
 [35.01 23.48 21.39 32.72 25.09 25.26 24.84 25.59 25.93 39.23]
 [21.53 33.20 25.53 32.60 26.92 20.55 37.11 32.48 22.07 31.19]
 [28.06 26.99 28.58 28.22 20.25 28.41 27.65 39.66 31.75 34.00]
 [27.56 39.41 35.89 26.4

In [3]:
for n in range(10):
    print(n, np.sum(data.Cp[n, :] * data.Dp))


0 88525.78315850289
1 87298.53831232604
2 77945.78451964573
3 79287.71506010283
4 82404.90572998105
5 84271.54812492567
6 82728.44472438304
7 88033.21375956495
8 89727.56402466634
9 75961.51986264331


In [4]:
cost = data.Cp



inactive = np.where(solution.S1_active == 0)[0]
active = np.where(solution.S1_active == 1)[0]
print(active)
# if not inactive.size or not active.size:
#     continue
# # cheapest inactive edge
# costs_in = cost[0, inactive]
# j = inactive[np.argmin(costs_in)]
# # most expensive active edge
# costs_ac = cost[0, active]
# k = active[np.argmax(costs_ac)]
# new_chrom = swap_bits(chromosome, k, j)
# setattr(solution_copy, chromosome_attr, new_chrom)

AttributeError: 'Solution' object has no attribute 'S1_active'